apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  containers:
  - name: web1
    image: nginx
    ports:
    - name: web1
      containerPort: 80
  - name: web2
    image: almalinux
    command: ["sleep", "200"]
    ports:
    - name: web2
      containerPort: 80
     