apiVersion: v1
kind: Pod
metadata:
  name: env
spec:
  containers:
  - name: web
    image: nginx
    env:
    - name: USERNAME
      value: "venkat"
    - name: PASSWORD
      value: "venkat123"
    ports:
    - name: web
      containerPort: 80
      protocol: TCP

