apiVersion: v1
kind: Pod
metadata:
  name: get-env
spec:
  containers:
  - name: web
    image: nginx
    envfrom:
    - name: person-name
      valueFrom:
        cofigMapKeyRef:
          name: configmap
          key: NAME
    - name: user-name
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: USER
    - name: password
      valueFrom:
        configMapKeyRef:
          name: configmap
          key: PASSWORD