apiVersion: v1
kind: Pod
metadata:
  name: get-multi-env
spec:
  containers:
  - name: web
    image: nginx
    envfrom:
    - configMapRef:
      name: configmap
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  USER: "venkat"
  PASSWORD: "venkat123"