apiVersion: v1
kind: Pod
metadata: 
  name: web
  labels:
    environment: dev
    project: roboshop
    component: web
spec:
  container:
  - name: web
    image: nginx
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: service
metadata: 
  name: clusterip
spec:
  selector:
    environment: dev
    project: roboshop
    component: web
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: web

   