apiVersion: v1
kind: Pod
metadata:
  name: web-with-nodeport-service
  labels:
    project: roboshop
    environment: dev
    component: web
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    project: roboshop
    environment: dev
    component: web
  ports:
  - name: nodeport
    port: 80 
    protocol: TCP
    targetPort: web  

