apiVersion: v1
kind:
metadata:
  name: web-with-loadbalancer-service
  labels:
    project: roboshop
    environment: dev
spec:
  containers:
  - name: web
    image: nginx
    ports:
    - name: http-web-service
      containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  selector:
    project: roboshop
    environment: dev
  ports:
  - name: loadbalncer-port
    port: 80
    protocol: TCP
    targetPort: http-web-service
